version: "3"
services:
  skipper:
    #image: dalongrong/skipper:latest
    build: ./
    image: dalongrong/skipper-docker-build-luarocks
    ports:
    - "9090:9090"
    - "9911:9911"
    volumes:
    - "./router.eskip:/router.eskip"
    - "./app.lua:/app.lua"
    command: skipper -enable-ratelimits -enable-prometheus-metrics -routes-file /router.eskip
  g:
    image: grafana/grafana
    ports:
    - "3000:3000"
  web:
    build: 
      context: ./
      dockerfile: Dockerfile-ip
    image: dalongrong/openresty-ip
    ports:
    - "8099:80"
    - "8100:88"
  p:
    image: prom/prometheus
    volumes:
    - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
    - "9091:9090"